# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyCharmProjects\rp_air\ui\rp_air_main_ui.ui'
#
# Created: Wed Apr 15 14:21:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(810, 550)
        MainWindow.setMinimumSize(QtCore.QSize(810, 550))
        MainWindow.setMaximumSize(QtCore.QSize(810, 550))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(125, 125, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_refresh_data = QtGui.QPushButton(self.centralwidget)
        self.pushButton_refresh_data.setGeometry(QtCore.QRect(570, 460, 231, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_refresh_data.setPalette(palette)
        self.pushButton_refresh_data.setAutoFillBackground(False)
        self.pushButton_refresh_data.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_refresh_data.setObjectName(_fromUtf8("pushButton_refresh_data"))
        self.groupBox_analysis_today = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_analysis_today.setGeometry(QtCore.QRect(10, 160, 551, 171))
        self.groupBox_analysis_today.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_analysis_today.setObjectName(_fromUtf8("groupBox_analysis_today"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_analysis_today)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 528, 142))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_analysis_today = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_analysis_today.setMargin(0)
        self.gridLayout_analysis_today.setObjectName(_fromUtf8("gridLayout_analysis_today"))
        self.label_analysis_time = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_time.sizePolicy().hasHeightForWidth())
        self.label_analysis_time.setSizePolicy(sizePolicy)
        self.label_analysis_time.setMinimumSize(QtCore.QSize(200, 30))
        self.label_analysis_time.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_time.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_time.setLineWidth(1)
        self.label_analysis_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_time.setObjectName(_fromUtf8("label_analysis_time"))
        self.gridLayout_analysis_today.addWidget(self.label_analysis_time, 0, 0, 1, 1)
        self.gridLayout_analysis_today_table = QtGui.QGridLayout()
        self.gridLayout_analysis_today_table.setObjectName(_fromUtf8("gridLayout_analysis_today_table"))
        self.label_analysis_header = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_header.setSizePolicy(sizePolicy)
        self.label_analysis_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_header.setLineWidth(1)
        self.label_analysis_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_header.setObjectName(_fromUtf8("label_analysis_header"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_header, 0, 0, 1, 1)
        self.label_analysis_pm25_today_04 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_today_04.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_today_04.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_today_04.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_today_04.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_today_04.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_today_04.setLineWidth(1)
        self.label_analysis_pm25_today_04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_today_04.setObjectName(_fromUtf8("label_analysis_pm25_today_04"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm25_today_04, 2, 4, 1, 1)
        self.label_analysis_pm10_today_03 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_today_03.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_today_03.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_today_03.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_today_03.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_today_03.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_today_03.setLineWidth(1)
        self.label_analysis_pm10_today_03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_today_03.setObjectName(_fromUtf8("label_analysis_pm10_today_03"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm10_today_03, 1, 3, 1, 1)
        self.label_analysis_pm25_today_01 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_today_01.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_today_01.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_today_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_today_01.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_today_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_today_01.setLineWidth(1)
        self.label_analysis_pm25_today_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_today_01.setObjectName(_fromUtf8("label_analysis_pm25_today_01"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm25_today_01, 2, 1, 1, 1)
        self.label_analysis_pm10_column = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_column.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_column.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_column.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_column.setLineWidth(1)
        self.label_analysis_pm10_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_column.setObjectName(_fromUtf8("label_analysis_pm10_column"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm10_column, 1, 0, 1, 1)
        self.label_analysis_city_01_header = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_01_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_01_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_01_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_01_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_01_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_01_header.setLineWidth(1)
        self.label_analysis_city_01_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_01_header.setObjectName(_fromUtf8("label_analysis_city_01_header"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_city_01_header, 0, 1, 1, 1)
        self.label_analysis_pm10_today_01 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_today_01.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_today_01.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_today_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_today_01.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_today_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_today_01.setLineWidth(1)
        self.label_analysis_pm10_today_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_today_01.setObjectName(_fromUtf8("label_analysis_pm10_today_01"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm10_today_01, 1, 1, 1, 1)
        self.label_analysis_city_04_header = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_04_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_04_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_04_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_04_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_04_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_04_header.setLineWidth(1)
        self.label_analysis_city_04_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_04_header.setObjectName(_fromUtf8("label_analysis_city_04_header"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_city_04_header, 0, 4, 1, 1)
        self.label_analysis_city_02_header = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_02_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_02_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_02_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_02_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_02_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_02_header.setLineWidth(1)
        self.label_analysis_city_02_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_02_header.setObjectName(_fromUtf8("label_analysis_city_02_header"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_city_02_header, 0, 2, 1, 1)
        self.label_analysis_pm25_column = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_column.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_column.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_column.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_column.setLineWidth(1)
        self.label_analysis_pm25_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_column.setObjectName(_fromUtf8("label_analysis_pm25_column"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm25_column, 2, 0, 1, 1)
        self.label_analysis_pm25_today_02 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_today_02.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_today_02.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_today_02.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_today_02.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_today_02.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_today_02.setLineWidth(1)
        self.label_analysis_pm25_today_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_today_02.setObjectName(_fromUtf8("label_analysis_pm25_today_02"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm25_today_02, 2, 2, 1, 1)
        self.label_analysis_pm10_today_04 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_today_04.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_today_04.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_today_04.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_today_04.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_today_04.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_today_04.setLineWidth(1)
        self.label_analysis_pm10_today_04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_today_04.setObjectName(_fromUtf8("label_analysis_pm10_today_04"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm10_today_04, 1, 4, 1, 1)
        self.label_analysis_pm10_today_02 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_today_02.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_today_02.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_today_02.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_today_02.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_today_02.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_today_02.setLineWidth(1)
        self.label_analysis_pm10_today_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_today_02.setObjectName(_fromUtf8("label_analysis_pm10_today_02"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm10_today_02, 1, 2, 1, 1)
        self.label_analysis_city_03_header = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_03_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_03_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_03_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_03_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_03_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_03_header.setLineWidth(1)
        self.label_analysis_city_03_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_03_header.setObjectName(_fromUtf8("label_analysis_city_03_header"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_city_03_header, 0, 3, 1, 1)
        self.label_analysis_pm25_today_03 = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_today_03.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_today_03.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_today_03.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_today_03.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_today_03.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_today_03.setLineWidth(1)
        self.label_analysis_pm25_today_03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_today_03.setObjectName(_fromUtf8("label_analysis_pm25_today_03"))
        self.gridLayout_analysis_today_table.addWidget(self.label_analysis_pm25_today_03, 2, 3, 1, 1)
        self.gridLayout_analysis_today.addLayout(self.gridLayout_analysis_today_table, 1, 0, 1, 1)
        self.groupBox_analysis_tomorrow = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_analysis_tomorrow.setGeometry(QtCore.QRect(10, 340, 551, 171))
        self.groupBox_analysis_tomorrow.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_analysis_tomorrow.setObjectName(_fromUtf8("groupBox_analysis_tomorrow"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox_analysis_tomorrow)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 528, 142))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_analysis_tomorrow = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_analysis_tomorrow.setMargin(0)
        self.gridLayout_analysis_tomorrow.setObjectName(_fromUtf8("gridLayout_analysis_tomorrow"))
        self.label_analysis_tomorrow_title = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_tomorrow_title.sizePolicy().hasHeightForWidth())
        self.label_analysis_tomorrow_title.setSizePolicy(sizePolicy)
        self.label_analysis_tomorrow_title.setMinimumSize(QtCore.QSize(200, 30))
        self.label_analysis_tomorrow_title.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_tomorrow_title.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_tomorrow_title.setLineWidth(1)
        self.label_analysis_tomorrow_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_tomorrow_title.setObjectName(_fromUtf8("label_analysis_tomorrow_title"))
        self.gridLayout_analysis_tomorrow.addWidget(self.label_analysis_tomorrow_title, 0, 0, 1, 1)
        self.gridLayout_analysis_tomorrow_table = QtGui.QGridLayout()
        self.gridLayout_analysis_tomorrow_table.setObjectName(_fromUtf8("gridLayout_analysis_tomorrow_table"))
        self.label_analysis_pm25_tomorrow_column = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_tomorrow_column.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_tomorrow_column.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_tomorrow_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_tomorrow_column.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_tomorrow_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_tomorrow_column.setLineWidth(1)
        self.label_analysis_pm25_tomorrow_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_tomorrow_column.setObjectName(_fromUtf8("label_analysis_pm25_tomorrow_column"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm25_tomorrow_column, 2, 0, 1, 1)
        self.label_analysis_pm25_tomorrow_02 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_tomorrow_02.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_tomorrow_02.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_tomorrow_02.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_tomorrow_02.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_tomorrow_02.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_tomorrow_02.setLineWidth(1)
        self.label_analysis_pm25_tomorrow_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_tomorrow_02.setObjectName(_fromUtf8("label_analysis_pm25_tomorrow_02"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm25_tomorrow_02, 2, 2, 1, 1)
        self.label_analysis_city_02_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_02_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_02_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_02_tomorrow_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_02_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_02_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_02_tomorrow_header.setLineWidth(1)
        self.label_analysis_city_02_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_02_tomorrow_header.setObjectName(_fromUtf8("label_analysis_city_02_tomorrow_header"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_city_02_tomorrow_header, 0, 2, 1, 1)
        self.label_analysis_pm25_tomorrow_04 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_tomorrow_04.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_tomorrow_04.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_tomorrow_04.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_tomorrow_04.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_tomorrow_04.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_tomorrow_04.setLineWidth(1)
        self.label_analysis_pm25_tomorrow_04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_tomorrow_04.setObjectName(_fromUtf8("label_analysis_pm25_tomorrow_04"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm25_tomorrow_04, 2, 4, 1, 1)
        self.label_analysis_city_04_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_04_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_04_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_04_tomorrow_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_04_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_04_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_04_tomorrow_header.setLineWidth(1)
        self.label_analysis_city_04_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_04_tomorrow_header.setObjectName(_fromUtf8("label_analysis_city_04_tomorrow_header"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_city_04_tomorrow_header, 0, 4, 1, 1)
        self.label_analysis_pm10_tomorrow_column = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_tomorrow_column.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_tomorrow_column.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_tomorrow_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_tomorrow_column.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_tomorrow_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_tomorrow_column.setLineWidth(1)
        self.label_analysis_pm10_tomorrow_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_tomorrow_column.setObjectName(_fromUtf8("label_analysis_pm10_tomorrow_column"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm10_tomorrow_column, 1, 0, 1, 1)
        self.label_analysis_pm10_tomorrow_03 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_tomorrow_03.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_tomorrow_03.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_tomorrow_03.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_tomorrow_03.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_tomorrow_03.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_tomorrow_03.setLineWidth(1)
        self.label_analysis_pm10_tomorrow_03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_tomorrow_03.setObjectName(_fromUtf8("label_analysis_pm10_tomorrow_03"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm10_tomorrow_03, 1, 3, 1, 1)
        self.label_analysis_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_analysis_tomorrow_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_tomorrow_header.setLineWidth(1)
        self.label_analysis_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_tomorrow_header.setObjectName(_fromUtf8("label_analysis_tomorrow_header"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_tomorrow_header, 0, 0, 1, 1)
        self.label_analysis_pm10_tomorrow_04 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_tomorrow_04.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_tomorrow_04.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_tomorrow_04.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_tomorrow_04.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_tomorrow_04.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_tomorrow_04.setLineWidth(1)
        self.label_analysis_pm10_tomorrow_04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_tomorrow_04.setObjectName(_fromUtf8("label_analysis_pm10_tomorrow_04"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm10_tomorrow_04, 1, 4, 1, 1)
        self.label_analysis_pm25_tomorrow_01 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_tomorrow_01.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_tomorrow_01.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_tomorrow_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_tomorrow_01.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_tomorrow_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_tomorrow_01.setLineWidth(1)
        self.label_analysis_pm25_tomorrow_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_tomorrow_01.setObjectName(_fromUtf8("label_analysis_pm25_tomorrow_01"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm25_tomorrow_01, 2, 1, 1, 1)
        self.label_analysis_pm10_tomorrow_01 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_tomorrow_01.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_tomorrow_01.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_tomorrow_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_tomorrow_01.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_tomorrow_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_tomorrow_01.setLineWidth(1)
        self.label_analysis_pm10_tomorrow_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_tomorrow_01.setObjectName(_fromUtf8("label_analysis_pm10_tomorrow_01"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm10_tomorrow_01, 1, 1, 1, 1)
        self.label_analysis_city_01_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_01_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_01_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_01_tomorrow_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_01_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_01_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_01_tomorrow_header.setLineWidth(1)
        self.label_analysis_city_01_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_01_tomorrow_header.setObjectName(_fromUtf8("label_analysis_city_01_tomorrow_header"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_city_01_tomorrow_header, 0, 1, 1, 1)
        self.label_analysis_pm25_tomorrow_03 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm25_tomorrow_03.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm25_tomorrow_03.setSizePolicy(sizePolicy)
        self.label_analysis_pm25_tomorrow_03.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm25_tomorrow_03.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm25_tomorrow_03.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm25_tomorrow_03.setLineWidth(1)
        self.label_analysis_pm25_tomorrow_03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm25_tomorrow_03.setObjectName(_fromUtf8("label_analysis_pm25_tomorrow_03"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm25_tomorrow_03, 2, 3, 1, 1)
        self.label_analysis_pm10_tomorrow_02 = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_pm10_tomorrow_02.sizePolicy().hasHeightForWidth())
        self.label_analysis_pm10_tomorrow_02.setSizePolicy(sizePolicy)
        self.label_analysis_pm10_tomorrow_02.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_pm10_tomorrow_02.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_pm10_tomorrow_02.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_pm10_tomorrow_02.setLineWidth(1)
        self.label_analysis_pm10_tomorrow_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_pm10_tomorrow_02.setObjectName(_fromUtf8("label_analysis_pm10_tomorrow_02"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_pm10_tomorrow_02, 1, 2, 1, 1)
        self.label_analysis_city_03_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_city_03_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_analysis_city_03_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_analysis_city_03_tomorrow_header.setMinimumSize(QtCore.QSize(100, 30))
        self.label_analysis_city_03_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_analysis_city_03_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_analysis_city_03_tomorrow_header.setLineWidth(1)
        self.label_analysis_city_03_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_analysis_city_03_tomorrow_header.setObjectName(_fromUtf8("label_analysis_city_03_tomorrow_header"))
        self.gridLayout_analysis_tomorrow_table.addWidget(self.label_analysis_city_03_tomorrow_header, 0, 3, 1, 1)
        self.gridLayout_analysis_tomorrow.addLayout(self.gridLayout_analysis_tomorrow_table, 1, 0, 1, 1)
        self.groupBox_forecast = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_forecast.setGeometry(QtCore.QRect(10, 10, 431, 131))
        self.groupBox_forecast.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_forecast.setCheckable(False)
        self.groupBox_forecast.setObjectName(_fromUtf8("groupBox_forecast"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_forecast)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 408, 104))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_forecast = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_forecast.setMargin(0)
        self.gridLayout_forecast.setObjectName(_fromUtf8("gridLayout_forecast"))
        self.label_forecast_today_header = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_today_header.sizePolicy().hasHeightForWidth())
        self.label_forecast_today_header.setSizePolicy(sizePolicy)
        self.label_forecast_today_header.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_today_header.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_today_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_today_header.setLineWidth(1)
        self.label_forecast_today_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_today_header.setObjectName(_fromUtf8("label_forecast_today_header"))
        self.gridLayout_forecast.addWidget(self.label_forecast_today_header, 0, 0, 1, 1)
        self.label_forecast_tomorrow_header = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_tomorrow_header.sizePolicy().hasHeightForWidth())
        self.label_forecast_tomorrow_header.setSizePolicy(sizePolicy)
        self.label_forecast_tomorrow_header.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_tomorrow_header.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_tomorrow_header.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_tomorrow_header.setLineWidth(1)
        self.label_forecast_tomorrow_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_tomorrow_header.setObjectName(_fromUtf8("label_forecast_tomorrow_header"))
        self.gridLayout_forecast.addWidget(self.label_forecast_tomorrow_header, 0, 1, 1, 1)
        self.label_forecast_today_time = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_today_time.sizePolicy().hasHeightForWidth())
        self.label_forecast_today_time.setSizePolicy(sizePolicy)
        self.label_forecast_today_time.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_today_time.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_today_time.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_today_time.setLineWidth(1)
        self.label_forecast_today_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_today_time.setObjectName(_fromUtf8("label_forecast_today_time"))
        self.gridLayout_forecast.addWidget(self.label_forecast_today_time, 1, 0, 1, 1)
        self.label_forecast_tomorrow_time = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_tomorrow_time.sizePolicy().hasHeightForWidth())
        self.label_forecast_tomorrow_time.setSizePolicy(sizePolicy)
        self.label_forecast_tomorrow_time.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_tomorrow_time.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_tomorrow_time.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_tomorrow_time.setLineWidth(1)
        self.label_forecast_tomorrow_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_tomorrow_time.setObjectName(_fromUtf8("label_forecast_tomorrow_time"))
        self.gridLayout_forecast.addWidget(self.label_forecast_tomorrow_time, 1, 1, 1, 1)
        self.label_forecast_today_status = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_today_status.sizePolicy().hasHeightForWidth())
        self.label_forecast_today_status.setSizePolicy(sizePolicy)
        self.label_forecast_today_status.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_today_status.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_today_status.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_today_status.setLineWidth(1)
        self.label_forecast_today_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_today_status.setObjectName(_fromUtf8("label_forecast_today_status"))
        self.gridLayout_forecast.addWidget(self.label_forecast_today_status, 2, 0, 1, 1)
        self.label_forecast_tomorrow_status = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_forecast_tomorrow_status.sizePolicy().hasHeightForWidth())
        self.label_forecast_tomorrow_status.setSizePolicy(sizePolicy)
        self.label_forecast_tomorrow_status.setMinimumSize(QtCore.QSize(200, 30))
        self.label_forecast_tomorrow_status.setFrameShape(QtGui.QFrame.Box)
        self.label_forecast_tomorrow_status.setFrameShadow(QtGui.QFrame.Plain)
        self.label_forecast_tomorrow_status.setLineWidth(1)
        self.label_forecast_tomorrow_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_forecast_tomorrow_status.setObjectName(_fromUtf8("label_forecast_tomorrow_status"))
        self.gridLayout_forecast.addWidget(self.label_forecast_tomorrow_status, 2, 1, 1, 1)
        self.groupBox_cai = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_cai.setGeometry(QtCore.QRect(570, 20, 230, 431))
        self.groupBox_cai.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_cai.setObjectName(_fromUtf8("groupBox_cai"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_cai)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_cai = QtGui.QGridLayout()
        self.gridLayout_cai.setObjectName(_fromUtf8("gridLayout_cai"))
        self.gridLayout_cai_header = QtGui.QGridLayout()
        self.gridLayout_cai_header.setObjectName(_fromUtf8("gridLayout_cai_header"))
        self.label_cai_time = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_time.sizePolicy().hasHeightForWidth())
        self.label_cai_time.setSizePolicy(sizePolicy)
        self.label_cai_time.setMinimumSize(QtCore.QSize(200, 30))
        self.label_cai_time.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_time.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_time.setLineWidth(1)
        self.label_cai_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_time.setObjectName(_fromUtf8("label_cai_time"))
        self.gridLayout_cai_header.addWidget(self.label_cai_time, 0, 0, 1, 1)
        self.gridLayout_cai.addLayout(self.gridLayout_cai_header, 0, 0, 1, 1)
        self.gridLayout_cai_table = QtGui.QGridLayout()
        self.gridLayout_cai_table.setObjectName(_fromUtf8("gridLayout_cai_table"))
        self.label_cai_cai_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_cai_column.sizePolicy().hasHeightForWidth())
        self.label_cai_cai_column.setSizePolicy(sizePolicy)
        self.label_cai_cai_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_cai_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_cai_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_cai_column.setLineWidth(1)
        self.label_cai_cai_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_cai_column.setObjectName(_fromUtf8("label_cai_cai_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_cai_column, 7, 0, 1, 1)
        self.label_cai_pm10_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_pm10_column.sizePolicy().hasHeightForWidth())
        self.label_cai_pm10_column.setSizePolicy(sizePolicy)
        self.label_cai_pm10_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_pm10_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_pm10_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_pm10_column.setLineWidth(1)
        self.label_cai_pm10_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_pm10_column.setObjectName(_fromUtf8("label_cai_pm10_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_pm10_column, 5, 0, 1, 1)
        self.label_cai_o3_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_o3_column.sizePolicy().hasHeightForWidth())
        self.label_cai_o3_column.setSizePolicy(sizePolicy)
        self.label_cai_o3_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_o3_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_o3_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_o3_column.setLineWidth(1)
        self.label_cai_o3_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_o3_column.setObjectName(_fromUtf8("label_cai_o3_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_o3_column, 3, 0, 1, 1)
        self.label_cai_pm25_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_pm25_01.sizePolicy().hasHeightForWidth())
        self.label_cai_pm25_01.setSizePolicy(sizePolicy)
        self.label_cai_pm25_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_pm25_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_pm25_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_pm25_01.setLineWidth(1)
        self.label_cai_pm25_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_pm25_01.setObjectName(_fromUtf8("label_cai_pm25_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_pm25_01, 6, 1, 1, 1)
        self.label_cai_o3_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_o3_01.sizePolicy().hasHeightForWidth())
        self.label_cai_o3_01.setSizePolicy(sizePolicy)
        self.label_cai_o3_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_o3_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_o3_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_o3_01.setLineWidth(1)
        self.label_cai_o3_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_o3_01.setObjectName(_fromUtf8("label_cai_o3_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_o3_01, 3, 1, 1, 1)
        self.label_cai_co_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_co_column.sizePolicy().hasHeightForWidth())
        self.label_cai_co_column.setSizePolicy(sizePolicy)
        self.label_cai_co_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_co_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_co_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_co_column.setLineWidth(1)
        self.label_cai_co_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_co_column.setObjectName(_fromUtf8("label_cai_co_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_co_column, 4, 0, 1, 1)
        self.label_cai_co_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_co_01.sizePolicy().hasHeightForWidth())
        self.label_cai_co_01.setSizePolicy(sizePolicy)
        self.label_cai_co_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_co_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_co_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_co_01.setLineWidth(1)
        self.label_cai_co_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_co_01.setObjectName(_fromUtf8("label_cai_co_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_co_01, 4, 1, 1, 1)
        self.label_cai_pm25_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_pm25_column.sizePolicy().hasHeightForWidth())
        self.label_cai_pm25_column.setSizePolicy(sizePolicy)
        self.label_cai_pm25_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_pm25_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_pm25_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_pm25_column.setLineWidth(1)
        self.label_cai_pm25_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_pm25_column.setObjectName(_fromUtf8("label_cai_pm25_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_pm25_column, 6, 0, 1, 1)
        self.label_cai_status_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_status_01.sizePolicy().hasHeightForWidth())
        self.label_cai_status_01.setSizePolicy(sizePolicy)
        self.label_cai_status_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_status_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_status_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_status_01.setLineWidth(1)
        self.label_cai_status_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_status_01.setObjectName(_fromUtf8("label_cai_status_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_status_01, 8, 1, 1, 1)
        self.label_cai_city_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_city_column.sizePolicy().hasHeightForWidth())
        self.label_cai_city_column.setSizePolicy(sizePolicy)
        self.label_cai_city_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_city_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_city_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_city_column.setLineWidth(1)
        self.label_cai_city_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_city_column.setObjectName(_fromUtf8("label_cai_city_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_city_column, 0, 0, 1, 1)
        self.label_cai_maxstatus_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_maxstatus_01.sizePolicy().hasHeightForWidth())
        self.label_cai_maxstatus_01.setSizePolicy(sizePolicy)
        self.label_cai_maxstatus_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_maxstatus_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_maxstatus_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_maxstatus_01.setLineWidth(1)
        self.label_cai_maxstatus_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_maxstatus_01.setObjectName(_fromUtf8("label_cai_maxstatus_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_maxstatus_01, 9, 1, 1, 1)
        self.label_cai_cai_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_cai_01.sizePolicy().hasHeightForWidth())
        self.label_cai_cai_01.setSizePolicy(sizePolicy)
        self.label_cai_cai_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_cai_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_cai_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_cai_01.setLineWidth(1)
        self.label_cai_cai_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_cai_01.setObjectName(_fromUtf8("label_cai_cai_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_cai_01, 7, 1, 1, 1)
        self.label_cai_so2_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_so2_column.sizePolicy().hasHeightForWidth())
        self.label_cai_so2_column.setSizePolicy(sizePolicy)
        self.label_cai_so2_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_so2_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_so2_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_so2_column.setLineWidth(1)
        self.label_cai_so2_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_so2_column.setObjectName(_fromUtf8("label_cai_so2_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_so2_column, 1, 0, 1, 1)
        self.label_cai_so2_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_so2_01.sizePolicy().hasHeightForWidth())
        self.label_cai_so2_01.setSizePolicy(sizePolicy)
        self.label_cai_so2_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_so2_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_so2_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_so2_01.setLineWidth(1)
        self.label_cai_so2_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_so2_01.setObjectName(_fromUtf8("label_cai_so2_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_so2_01, 1, 1, 1, 1)
        self.label_cai_pm10_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_pm10_01.sizePolicy().hasHeightForWidth())
        self.label_cai_pm10_01.setSizePolicy(sizePolicy)
        self.label_cai_pm10_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_pm10_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_pm10_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_pm10_01.setLineWidth(1)
        self.label_cai_pm10_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_pm10_01.setObjectName(_fromUtf8("label_cai_pm10_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_pm10_01, 5, 1, 1, 1)
        self.label_cai_no2_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_no2_column.sizePolicy().hasHeightForWidth())
        self.label_cai_no2_column.setSizePolicy(sizePolicy)
        self.label_cai_no2_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_no2_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_no2_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_no2_column.setLineWidth(1)
        self.label_cai_no2_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_no2_column.setObjectName(_fromUtf8("label_cai_no2_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_no2_column, 2, 0, 1, 1)
        self.label_cai_no2_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_no2_01.sizePolicy().hasHeightForWidth())
        self.label_cai_no2_01.setSizePolicy(sizePolicy)
        self.label_cai_no2_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_no2_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_no2_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_no2_01.setLineWidth(1)
        self.label_cai_no2_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_no2_01.setObjectName(_fromUtf8("label_cai_no2_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_no2_01, 2, 1, 1, 1)
        self.label_cai_status_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_status_column.sizePolicy().hasHeightForWidth())
        self.label_cai_status_column.setSizePolicy(sizePolicy)
        self.label_cai_status_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_status_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_status_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_status_column.setLineWidth(1)
        self.label_cai_status_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_status_column.setObjectName(_fromUtf8("label_cai_status_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_status_column, 8, 0, 1, 1)
        self.label_cai_maxstatus_column = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_maxstatus_column.sizePolicy().hasHeightForWidth())
        self.label_cai_maxstatus_column.setSizePolicy(sizePolicy)
        self.label_cai_maxstatus_column.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_maxstatus_column.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_maxstatus_column.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_maxstatus_column.setLineWidth(1)
        self.label_cai_maxstatus_column.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_maxstatus_column.setObjectName(_fromUtf8("label_cai_maxstatus_column"))
        self.gridLayout_cai_table.addWidget(self.label_cai_maxstatus_column, 9, 0, 1, 1)
        self.label_cai_city_01 = QtGui.QLabel(self.groupBox_cai)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cai_city_01.sizePolicy().hasHeightForWidth())
        self.label_cai_city_01.setSizePolicy(sizePolicy)
        self.label_cai_city_01.setMinimumSize(QtCore.QSize(100, 30))
        self.label_cai_city_01.setFrameShape(QtGui.QFrame.Box)
        self.label_cai_city_01.setFrameShadow(QtGui.QFrame.Plain)
        self.label_cai_city_01.setLineWidth(1)
        self.label_cai_city_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cai_city_01.setObjectName(_fromUtf8("label_cai_city_01"))
        self.gridLayout_cai_table.addWidget(self.label_cai_city_01, 0, 1, 1, 1)
        self.gridLayout_cai.addLayout(self.gridLayout_cai_table, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_cai, 0, 0, 1, 1)
        self.pushButton_forecast = QtGui.QPushButton(self.centralwidget)
        self.pushButton_forecast.setGeometry(QtCore.QRect(450, 20, 111, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_forecast.setPalette(palette)
        self.pushButton_forecast.setAutoFillBackground(False)
        self.pushButton_forecast.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_forecast.setObjectName(_fromUtf8("pushButton_forecast"))
        self.pushButton_cai = QtGui.QPushButton(self.centralwidget)
        self.pushButton_cai.setGeometry(QtCore.QRect(450, 90, 111, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_cai.setPalette(palette)
        self.pushButton_cai.setAutoFillBackground(False)
        self.pushButton_cai.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_cai.setObjectName(_fromUtf8("pushButton_cai"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "인천 미세먼지 정보", None))
        self.pushButton_refresh_data.setText(_translate("MainWindow", "가져오기", None))
        self.groupBox_analysis_today.setTitle(_translate("MainWindow", "미세먼지 예보분석(오늘)", None))
        self.label_analysis_time.setText(_translate("MainWindow", "-", None))
        self.label_analysis_header.setText(_translate("MainWindow", "미세먼지", None))
        self.label_analysis_pm25_today_04.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_today_03.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm25_today_01.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_column.setText(_translate("MainWindow", "PM-10", None))
        self.label_analysis_city_01_header.setText(_translate("MainWindow", "인천", None))
        self.label_analysis_pm10_today_01.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_04_header.setText(_translate("MainWindow", "경기남부", None))
        self.label_analysis_city_02_header.setText(_translate("MainWindow", "서울", None))
        self.label_analysis_pm25_column.setText(_translate("MainWindow", "PM-2.5", None))
        self.label_analysis_pm25_today_02.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_today_04.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_today_02.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_03_header.setText(_translate("MainWindow", "경기북부", None))
        self.label_analysis_pm25_today_03.setText(_translate("MainWindow", "-", None))
        self.groupBox_analysis_tomorrow.setTitle(_translate("MainWindow", "미세먼지 예보분석(내일)", None))
        self.label_analysis_tomorrow_title.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm25_tomorrow_column.setText(_translate("MainWindow", "PM-2.5", None))
        self.label_analysis_pm25_tomorrow_02.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_02_tomorrow_header.setText(_translate("MainWindow", "서울", None))
        self.label_analysis_pm25_tomorrow_04.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_04_tomorrow_header.setText(_translate("MainWindow", "경기남부", None))
        self.label_analysis_pm10_tomorrow_column.setText(_translate("MainWindow", "PM-10", None))
        self.label_analysis_pm10_tomorrow_03.setText(_translate("MainWindow", "-", None))
        self.label_analysis_tomorrow_header.setText(_translate("MainWindow", "미세먼지", None))
        self.label_analysis_pm10_tomorrow_04.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm25_tomorrow_01.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_tomorrow_01.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_01_tomorrow_header.setText(_translate("MainWindow", "인천", None))
        self.label_analysis_pm25_tomorrow_03.setText(_translate("MainWindow", "-", None))
        self.label_analysis_pm10_tomorrow_02.setText(_translate("MainWindow", "-", None))
        self.label_analysis_city_03_tomorrow_header.setText(_translate("MainWindow", "경기북부", None))
        self.groupBox_forecast.setTitle(_translate("MainWindow", "미세먼지 예보현황(인천 전지역)", None))
        self.label_forecast_today_header.setText(_translate("MainWindow", "오늘예보", None))
        self.label_forecast_tomorrow_header.setText(_translate("MainWindow", "내일예보", None))
        self.label_forecast_today_time.setText(_translate("MainWindow", "-", None))
        self.label_forecast_tomorrow_time.setText(_translate("MainWindow", "-", None))
        self.label_forecast_today_status.setText(_translate("MainWindow", "-", None))
        self.label_forecast_tomorrow_status.setText(_translate("MainWindow", "-", None))
        self.groupBox_cai.setTitle(_translate("MainWindow", "통합대기환경지수(CAI)", None))
        self.label_cai_time.setText(_translate("MainWindow", "-", None))
        self.label_cai_cai_column.setText(_translate("MainWindow", "CAI 지수", None))
        self.label_cai_pm10_column.setText(_translate("MainWindow", "PM-10", None))
        self.label_cai_o3_column.setText(_translate("MainWindow", "O₃", None))
        self.label_cai_pm25_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_o3_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_co_column.setText(_translate("MainWindow", "CO", None))
        self.label_cai_co_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_pm25_column.setText(_translate("MainWindow", "PM-2.5", None))
        self.label_cai_status_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_city_column.setText(_translate("MainWindow", "측정소", None))
        self.label_cai_maxstatus_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_cai_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_so2_column.setText(_translate("MainWindow", "SO₂", None))
        self.label_cai_so2_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_pm10_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_no2_column.setText(_translate("MainWindow", "NO₂", None))
        self.label_cai_no2_01.setText(_translate("MainWindow", "-", None))
        self.label_cai_status_column.setText(_translate("MainWindow", "구분", None))
        self.label_cai_maxstatus_column.setText(_translate("MainWindow", "대표오염물질", None))
        self.label_cai_city_01.setText(_translate("MainWindow", "-", None))
        self.pushButton_forecast.setText(_translate("MainWindow", "웹 (예보)", None))
        self.pushButton_cai.setText(_translate("MainWindow", "웹 (CAI)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

